// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace entity_framework_in_class
{
    public partial class Member
    {
        public int MemberId { get; set; }
        public string? MemberName { get; set; }
        public string? Phone { get; set; }
        public string? Email { get; set; }
        public string? MemberAddress { get; set; }
        public string? Zip { get; set; }
        public string? Country { get; set; }
        public int? MembershipType { get; set; }

        public virtual Membership? MembershipTypeNavigation { get; set; }
    }
}