// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace entity_framework_in_class
{
    public partial class Membership
    {
        public Membership()
        {
            Member = new HashSet<Member>();
        }

        public int MembershipType { get; set; }
        public string? MembershipName { get; set; }

        public virtual ICollection<Member> Member { get; set; }
    }
}